### ISSUE TITLE
Initial Release

### ISSUE THREAD

**Issue by jlaehne** [hyperspy/rosettasciio#99]
## [v0.1](https://github.com/hyperspy/rosettasciio/milestone/1)
We have progressed quite far on preparing an initial release and improving consistency within RosettaSciIO as documented in the [milestone](https://github.com/hyperspy/rosettasciio/milestone/1). Therefore, we should aim for a timely initial release. Let's try to use this issue to speed up that process and see what is left. In principle, I think we could even release the current state.

However, it would be good to clarify the following points:
- [ ] #51
- [x] #14 (currently the test data blows up the project size)
- [ ] #69 
- [x] #79

Finally, there are a number of reported bugs that would be nice to get fixed (and most of them should be low hanging fruits):
- [ ] #37
- [x] #66 
- [x] #71
- [ ] #73
- [x] #82
- [x] #83 
- [x] #90
- [ ] #91 
- [x] #96

And of course, it is always good to
- #60

**Once, we are happy with the state, we need to**
- [x] Create release workflow file (#126)
- [x] Document releasing workflow (#126)
- [x] Create RosettaSciIO on pypi - this is setup with trusted publisher in #126
- [x] Zenodo is setup to create DOI and entry on creation of the github release. 
- [x] Do initial release on github - #126 set it up to create GitHub release after successfully generating sdist and wheel and uploading to pypi.org
- [ ] Create conda-forge feedstock

**Comment by jlaehne** [comment]
Do feel free to edit and add to the above list.

**Comment by ericpre** [comment]
We could merge the existing the PR ready to review and proceed with the release. The rest can be addressed in following releases.

**Comment by ericpre** [comment]
After #129 and #131 are done and merged, I think that we can proceed with the release, everything should be in place.

**Comment by jlaehne** [comment]
#55 and #87 are also ready for review and may be included in the initial release - though they should not hold back the release as we can then easily do follow-up releases.

**Comment by ericpre** [comment]
#11 is quite large and may take time to review - except it someone already started reviewing it?

**Comment by CSSFrancis** [comment]
I need to make some changes to #11 based on the changes introduced by #111 so I was kind of waiting before going back to it.  I would vote for going for the 0.1.0 release and then we can add it later.

**Comment by jlaehne** [comment]
The initial release is out: #133
